"""initial

Revision ID: 22a931ad27de
Revises: 
Create Date: 2019-10-16 20:36:55.438760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22a931ad27de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Students',
    sa.Column('student_no', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('email_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('student_no')
    )
    op.create_table('Teachers',
    sa.Column('teacher_no', sa.String(length=10), nullable=False),
    sa.Column('teacher_name', sa.String(length=10), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('teacher_no')
    )
    op.create_table('AuthInformation',
    sa.Column('auth_no', sa.String(length=20), nullable=False),
    sa.Column('auth_name', sa.String(length=10), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=18), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['auth_no'], ['Students.student_no'], ),
    sa.PrimaryKeyConstraint('auth_no')
    )
    op.create_table('Exams',
    sa.Column('exam_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_name', sa.String(length=30), nullable=True),
    sa.Column('exam_author', sa.String(length=10), nullable=False),
    sa.Column('exam_body', mysql.LONGTEXT(), nullable=True),
    sa.Column('raw_files', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('exam_time', sa.Integer(), nullable=True),
    sa.Column('score_count', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_author'], ['Teachers.teacher_no'], ),
    sa.PrimaryKeyConstraint('exam_no')
    )
    op.create_table('student_exam',
    sa.Column('student_no', sa.String(length=20), nullable=False),
    sa.Column('exam_no', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answer_status', mysql.LONGTEXT(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exam_no'], ['Exams.exam_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_no'], ['Students.student_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_no', 'exam_no')
    )
    op.create_table('title_compare',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_no', sa.Integer(), nullable=True),
    sa.Column('classify', sa.Integer(), nullable=True),
    sa.Column('question_no', sa.String(length=5), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['exam_no'], ['Exams.exam_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_compare')
    op.drop_table('student_exam')
    op.drop_table('Exams')
    op.drop_table('AuthInformation')
    op.drop_table('Teachers')
    op.drop_table('Students')
    # ### end Alembic commands ###
